FROM python:3.10

RUN curl -sSL https://install.python-poetry.org | python3 -

WORKDIR /code

COPY poetry.lock pyproject.toml /code/
RUN /root/.local/bin/poetry config virtualenvs.create false
RUN /root/.local/bin/poetry install --without dev --no-root --no-interaction

RUN pip install gunicorn
COPY . /code

CMD ["gunicorn", "{{package}}.app:app", "--host", "0.0.0.0", "--port", "8000"]
